odps:
  access_id: 
  access_key: 
  endpoint: http://service.cn.maxcompute.aliyun.com/api
  project: 

## hbase zeekooper地址，阿里云控制获取
hbase:
  zkAddress:

kafka:
  topics: log_hqbs_general
  groupId: CID_log_hqbs_general
  consumer:
    poll:
      timeount: 1000
